# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

checkRow <- function(x, maxRows, rowCol, wiggle) {
    .Call('_Nori_checkRow', PACKAGE = 'Nori', x, maxRows, rowCol, wiggle)
}

